server:
  port: 6080

spring:
  datasource:
    name: stock
    url: jdbc:mysql://192.168.8.129:3306/huaibeiqiquan
    #url: jdbc:mysql://192.168.1.12:3306/huaibeiqiquan
    username: ruanyun
    password: ruanyun
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  cache.jcache.config: ehcache3.xml
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qiquan.model